"""Pydantic models for AI SDK structured output.

These schemas are used with ai_sdk.generate_object() to get typed LLM responses
instead of manually parsing JSON strings.
"""
from __future__ import annotations

from pydantic import BaseModel, Field


# ── Share Card ──────────────────────────────────────────


class ShareCardMetric(BaseModel):
    label: str
    value: str


class ShareCardOutput(BaseModel):
    theme: str = "report"
    eyebrow: str = "INSIGHT REPORT"
    headline: str = Field(max_length=120)
    summary: str
    highlight: str | None = None
    evidence_quote: str | None = None
    evidence_source: str | None = None
    action_title: str | None = None
    action_detail: str | None = None
    metrics: list[ShareCardMetric] = Field(default_factory=list)
    footer: str = ""


# ── Evidence & Actions ──────────────────────────────────


class EvidenceItemOutput(BaseModel):
    note_id: str
    quote: str
    rationale: str


class ActionItemOutput(BaseModel):
    title: str
    detail: str
    priority: str = "medium"  # high | medium | low


# ── Insight Report (sub-agent / direct output) ─────────


class InsightReportOutput(BaseModel):
    """Schema for a single insight report generated by LLM."""

    title: str
    description: str
    type: str = "report"
    report_markdown: str
    confidence: float = Field(ge=0.0, le=1.0, default=0.7)
    importance_score: float = Field(ge=0.0, le=1.0, default=0.7)
    novelty_score: float = Field(ge=0.0, le=1.0, default=0.5)
    evidence_items: list[EvidenceItemOutput] = Field(default_factory=list)
    action_items: list[ActionItemOutput] = Field(default_factory=list)
    share_card: ShareCardOutput | None = None


# ── Multi-Agent Grouping (s0 orchestrator output) ──────


class NoteGroupOutput(BaseModel):
    angle: str
    note_ids: list[str]
    theme: str


class NoteGroupListOutput(BaseModel):
    """Schema for s0 orchestrator: groups of notes with analysis angles."""

    groups: list[NoteGroupOutput]


# ── Clustered Pipeline (angle discovery output) ────────


class AngleOutput(BaseModel):
    """A single analysis angle discovered from note clusters."""

    angle_name: str = Field(description="角度名称，2-6个字")
    description: str = Field(description="该角度要探索的问题，1-2句话")
    note_ids: list[str] = Field(description="该角度最相关的笔记ID列表")
    type_hint: str = Field(
        default="pattern",
        description="报告类型提示: pattern | connection | gap | trend | synthesis",
    )


class AngleListOutput(BaseModel):
    """Output of the angle discovery LLM call."""

    angles: list[AngleOutput]
